---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - docker_network_name is defined
      - application_name is defined
      - loki_url is defined
      - shared_secret is defined
      - cookie_secret is defined
      - idp_client_id is defined
      - idp_client_secret is defined
      - idp_service_account is defined
      - authenticate_virtual_host is defined
      - proxy_virtual_host is defined
      - pomerium_config_path is defined

- name: Create the dockernetwork
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create pomerium
  docker_container:
    name: "pomerium"
    image: "pomerium/pomerium:v0.25.1"
    restart_policy: "always"
    cleanup: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - "{{ hostvars[inventory_hostname].working_directory }}pomerium:/pomerium"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    networks:
      - name: "{{ docker_network_name }}"
      - name: "bridge"

- name: Copy pomerium config
  copy:
    src: "{{ pomerium_config_path }}"
    dest: "{{ hostvars[inventory_hostname].working_directory }}pomerium/config.yaml"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

# Restart the proxy
- name: Restart proxy
  command: docker restart pomerium
  register: restart_pomerium_result
  changed_when: restart_pomerium_result.rc != 0
